services:
  mariadb:
    image: mariadb
    environment: 
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
      - MARIADB_DATABASE=Info411_brawl
      - MARIADB_ROOT_PASSWORD=admin+
    ports:
      - 3306:3306
    volumes:
      - /home/elie/Documents/projetDocker/db_data:/var/lib/mysql
  monapache:
    image: delvarre/monapache
    volumes:
      - .:/var/www.html
    ports:
      - 80:80
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80
  monubuntu:
    image: delvarre/monubuntu