services:
  mariadb:
    image: mariadb
    environment: 
      - MARIADB_USER=${UTILISATEUR_BD}
      - MARIADB_PASSWORD=${MDP_BD}
      - MARIADB_DATABASE=${NOM_BD}
      - MARIADB_ROOT_PASSWORD=${MDP_ROOT}
    ports:
      - 3306:3306
    volumes:
      - /home/elie/Documents/projetDocker/db_data:/var/lib/mysql
  monapache:
    image: delvarre/monapache
    volumes:
      - .:/var/www.html
    ports:
      - "${PORT_SITE}:80"
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - "${PORT_PHPMYADMIN}:80"
  monubuntu:
    image: delvarre/monubuntu